--drop table ads
CREATE TABLE public.ads
(
	advertiser_id	bigint primary key,
	campaign_id	bigint REFERENCES campaigns (campaign_id),
	campaign_name	varchar,
	adgroup_id	bigint,
	adgroup_name	varchar,
	ad_id	bigint,
	ad_name	varchar,
	identity_id	varchar,
	identity_type	varchar,
	call_to_action	varchar,
	call_to_action_id	varchar,
	card_id	bigint,
	status	varchar,
	opt_status	varchar,
	is_aco	boolean,
	image_ids	varchar,
	ad_format	varchar,
	ad_text	varchar,
	ad_texts	varchar,
	video_id	varchar,
	app_name	varchar,
	landing_page_url	varchar,
	landing_page_urls	varchar,
	display_name	varchar,
	profile_image	varchar,
	impression_tracking_url	varchar,
	click_tracking_url	varchar,
	open_url	varchar,
	open_url_type	varchar,
	playable_url	varchar,
	page_id	bigint,
	vast_moat	bool,
	is_creative_authorized	bool,
	is_new_structure	bool,
	create_time	varchar,
	modify_time	varchar
)